# Generated by Django 3.0.5 on 2023-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_menu', models.CharField(max_length=200)),
                ('training_weight', models.IntegerField()),
                ('training_times', models.IntegerField()),
                ('training_set', models.IntegerField()),
            ],
        ),
    ]
