# Generated by Django 3.0.5 on 2023-10-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_training_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_parts', models.CharField(max_length=30)),
                ('training_name', models.CharField(max_length=30)),
                ('training_movie', models.URLField(blank=True)),
            ],
        ),
    ]
