# Generated by Django 3.0.5 on 2023-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
