# Generated by Django 3.0.5 on 2023-10-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_user_info_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend_history',
            name='recommend_name',
            field=models.CharField(max_length=3000),
        ),
    ]
